export const SALT_ROUNDS = 11;

export const JWT_CONSTANTS = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN,
};

export const EDUCATION = {
  CU_NHAN: 'Cử nhân',
  DANG_HOC_DAI_HOC: 'Đang học đại học',
  THPT: 'Trung học phổ thông',
  TIEN_SI: 'Tiến sĩ',
  THAC_SI: 'Thạc sĩ',
  SAU_DAI_HOC: 'Sau đại học',
  TRUONG_DAY_NGHE: 'Trường dạy nghề',
};

export const FUTURE_FAMILY = {
  MUON_CO_CON: 'Muốn có con',
  KHONG_MUON_CO_CON: 'Không muốn có con',
  CO_ROI_MUON_CO_THEM: 'Có rồi muốn có thêm',
  CO_ROI_KHONG_MUON_CO_THEM: 'Có rồi không muốn có thêm',
  CHUA_RO: 'Chưa rõ',
};

export const COMMUNICATION_STYLE = {
  NGHIEN_NHAN_TIN: 'Nghiên nhân tin',
  THICH_GOI_DIEN: 'Thích gọi điện',
  THICH_GOI_VIDEO: 'Thích gọi video',
  IT_NHAN_TIN: 'Ít nhận tin',
  THICH_GAP_MAT_TRUC_TIEP: 'Thích gặp mặt trực tiếp',
};

export const LOVE_LANGUAGE = {
  NHUNG_HANH_DONG_TINH_TE: 'Những hành động tình cảm',
  NHUNG_MON_QUA: 'Những món quà',
  NHUNG_CU_CHI_AU_YEM: 'Những cử chỉ ý yêu',
  NHUNG_LOI_KHEN: 'Những lời khén',
  THOI_GIAN_BEN_NHAU: 'Thời gian bên nhau',
};

export const PETS = {
  CHO: 'Chó',
  MEO: 'Mèo',
  BO_SAT: 'Bò sát',
  DONG_VAT_LUONG_CU: 'Động vật lưỡng cư',
  LOAI_CHIM: 'Loại chim',
  CA: 'Cá',
  RUA: 'Rùa',
  HAMSTER: 'Hamster',
  THO: 'Thỏ',
  KHAC: 'Khác',
  KHONG_NUOI_THU_CUNG: 'Không nuôi thú cưng',
  MUON_NUOI_THU_CUNG: 'Muốn nuôi thú cưng',
  DI_UNG_VOI_DONG_VAT: 'Dị ứng với động vật',
};

export const ALCOHOL_CONSUMPTION = {
  KHONG_DANH_CHO_MINH: 'Không đanh chọ mình',
  LUON_TINH_TAO: 'Luôn tỉnh táo',
  UONG_CO_TRACH_NGHIEM: 'Uống có trách nhiệm',
  CHI_NHUNG_DIP_DAC_BIET: 'Chỉ nhừng đợt đặc biệt',
  UONG_GIAO_LUU_VAO_CUOI_TUAN: 'Uống giao lưu vào cuối tuần',
  HAU_NHU_MOI_TOI: 'Hậu như mỗi tối',
};

export const SMOKING_PREFERENCE = {
  HUT_THUOC_VOI_BAN_BE: 'Hút thuốc với bạn bè',
  HUT_THUOC_KHI_NHAU: 'Hút thuốc khi nhàu',
  KHONG_HUT_THUOC: 'Không hút thuốc',
  HUT_THUOC_THUONG_XUYEN: 'Hút thuốc thường xuyên',
  DANG_CO_GANG_BO: 'Đang có gạng bụng',
};

export const EXERCISE_FREQUENCY = {
  HANG_NGAY: 'Hằng ngày',
  THUONG_XUYEN: 'Thường xuyên',
  THINH_THOANG: 'Thính thống',
  KHONG_TAP: 'Không tập',
};

export const DIETARY_PREFERENCE = {
  AN_THUAN_CHAY: 'An thuần chay',
  AN_CHAY: 'An chay',
  CHI_AN_HAI_SAN_RAU_CU: 'Chỉ ăn hai sản rau củ',
  CHI_AN_THIT: 'Chỉ ăn thịt',
  KHONG_AN_KIENG: 'Không ăn kiêng',
  KHAC: 'Khác',
};

export const SOCIAL_MEDIA_USAGE = {
  INFLUENCER: 'Influencer',
  HOAT_DONG_TICH_CUC: 'Hoạt động tích cực',
  KHONG_DUNG_MANG: 'Không dùng mạng',
  LUOT_DAO_AM_THAM: 'Lột da am thấm',
};

export const SLEEP_PATTERN = {
  DAY_SOM: 'Ngày sóm',
  CU_DEM: 'Củ đêm',
  GIO_GIAC_LINH_HOAT: 'Giờ giấc linh hoạt',
};

export const LOOKING_FOR = {
  NGUOI_YEU: 'Người yêu',
  HEN_HO_LAU_DAI: 'Bạn hẹn hò lâu dài',
  BAT_KI_DIEU_GI_CO_THE: 'Bất kì điều gì có thể',
  QUAN_HE_KHONG_RANG_BUOC: 'Quan hệ không ràng buộc',
  NHUNG_NGUOI_BAN_MOI: 'Những người bạn mới',
  CHUA_RO: 'Chưa rõ',
};

export const ZODIAC_SIGN = {
  BachDuong: 'Bạch Dương',
  KimNguu: 'Kim Ngưu',
  SongTu: 'Song Tử',
  CuGiai: 'Cự Giải',
  SuTu: 'Sư Tử',
  XuNu: 'Xử Nữ',
  ThienBinh: 'Thiên Bình',
  BoCap: 'Bọ Cạp',
  NhanMa: 'Nhân Mã',
  MaKet: 'Ma Kết',
  BaoBinh: 'Bảo Bình',
  SongNgu: 'Song Ngư',
};

export const GENDER = {
  MALE: 'Nam',
  FEMALE: 'Nữ',
  OTHER: 'Khác',
};

export const INTERESTS = {
  CHEO_THUYEN: 'Chèo thuyền',
  LAN: 'Lặn',
  MO_TO_NUOC: 'Môtô nước',
  TOUR_DI_BO: 'Tour đi bộ',
  TU_NHIEN: 'Tự nhiên',
  SUOI_NUOC_NONG: 'Suối nước nóng',
  DAT_CHO_DI_DAO: 'Đặt chỗ đi dạo',
  CHEO_CANO: 'Chèo canô',
  TRUOT_VAN_TUYET: 'Trượt ván tuyết',
  PHUOT: 'Phượt',
  DU_LICH_COUCHSURFING: 'Du lịch Couchsurfing',
  LAN_TU_DO: 'Lặn tự do',
  TRUOT_TUYET: 'Trượt tuyết',
  DU_LICH: 'Du lịch',
  CHEO_VAN_SUP: 'Chèo ván SUP',
  LUOT_SONG: 'Lướt sóng',
  BAR_BEN_BO_BIEN: 'Bar bên bờ biển',
  DU_LUON: 'Dù lượn',
  LEO_NUI_DA: 'Leo núi đá',
  THUYEN_BUOM: 'Thuyền buồm',
  DI_BO_DUONG_TRUONG: 'Đi bộ đường trường',
  NHUNG_NGON_NUI: 'Những ngọn núi',
  DU_LICH_BUI: 'Du lịch bụi',
  CAU_CA: 'Câu cá',
  CAM_TRANG: 'Cắm trại',
  HOAT_DONG_NGOAI_TROI: 'Hoạt động ngoài trời',
  DI_PICNIC: 'Đi picnic',
  THE_HE_9X: 'Thế hệ 9X',
  SU_KIEN_COMIC_CON: 'Sự kiện Comic Con',
  HARRY_POTTER: 'Harry Potter',
  NBA: 'NBA',
  MLB: 'MLB',
  POTTERHEAD: 'Potterhead',
  DUNGEONS_AND_DRAGONS: 'Dungeons & Dragons',
  MANGA: 'Manga',
  MARVEL: 'Marvel',
  DISNEY: 'Disney',
  THE_THAO_DIEN_TU: 'Thể thao điện tử',
  PLAYSTATION: 'PlayStation',
  FORTNITE: 'Fortnite',
  XBOX: 'Xbox',
  LIEN_MINH_HUYEN_THOAI: 'Liên Minh Huyền Thoại',
  ROBLOX: 'Roblox',
  NINTENDO: 'Nintendo',
  AMONG_US: 'Among Us',
  ATARI: 'Atari',
  QUYEN_CUA_NHOM_LGBTQIA: 'Quyền của nhóm LGBTQIA+',
  CHOI_ESCAPE_ROOM: 'Chơi escape room',
  QUAN_BAR: 'Quán bar',
  DO_SECONDHAND: 'Đồ secondhand',
  BAO_TANG: 'Bảo tàng',
  DI_QUAY: 'Đi quẩy',
  XEM_PHIM_NGOAI_TROI: 'Xem phim ngoài trời',
  LE_HOI: 'Lễ hội',
  XE_PHAN_KHOI_LON: 'Xe phân khối lớn',
  NHAC_KICH: 'Nhạc kịch',
  TRAI_NGHIEM_QUAN_CA_PHE: 'Trải nghiệm quán cà phê',
  THUY_CUNG: 'Thủy cung',
  MUA_SAM: 'Mua sắm',
  TRIEN_LAM_TRUNG_BAY: 'Triển lãm trưng bày',
  DI_CHILL_TAI_BAR: 'Đi chill tại bar',
  TIEC_GIA_DINH: 'Tiệc gia đình',
  XE_HOI: 'Xe hơi',
  NHAC_KICH_WEST_END: 'Nhạc kịch West End',
  SAN_KHAU_BROADWAY: 'Sân khấu Broadway',
  TRO_CAU_DO_TAI_QUAN_RUOU: 'Trò câu đố tại quán rượu',
  QUAN_CAFE: 'Quán café',
  HAPPY_HOUR: 'Happy hour',
  HAI_DOC_THOAI: 'Hài độc thoại',
  KARAOKE: 'Karaoke',
  NHA_HAT: 'Nhà hát',
  SHISHA: 'Shisha',
  ROLLERSKATING: 'Rollerskating',
  NHAC_LIVE: 'Nhạc live',
  CHOI_BOWLING: 'Chơi bowling',
  LIEN_HOAN_PHIM: 'Liên hoan phim',
  QUAN_RUOU: 'Quán rượu',
  KHAM_PHA_QUAN_BAR: 'Khám phá quán bar',
  TIEC_TUNG: 'Tiệc tùng',
  DI_CHOI_DEM: 'Đi chơi đêm',
  LAI_XE_MAY: 'Lái xe máy',
  TRIEN_LAM_NGHE_THUAT: 'Triển lãm nghệ thuật',
  HOA_NHAC: 'Hòa nhạc',
  CAC_LE_HOI_TRONG_THANH_PHO: 'Các lễ hội trong thành phố',
  DIEN_KINH: 'Điền kinh',
  BONG_CHUYEN_BAI_BIEN: 'Bóng chuyền bãi biển',
  JUDO: 'Judo',
  VO_MUAY_THAI: 'Võ Muay Thái',
  DI_DAO: 'Đi dạo',
  THE_THAO_BAI_BIEN: 'Thể thao bãi biển',
  LOP_THE_DUC_NHOM: 'Lớp thể dục nhóm',
  TRUOT_PATIN: 'Trượt patin',
  THE_THAO: 'Thể thao',
  QUYEN_ANH: 'Quyền anh',
  THE_DUC_DUNG_CU: 'Thể dục dụng cụ',
  BONG_BAU_DUC: 'Bóng bầu dục',
  CAU_LONG: 'Cầu lông',
  PILATES: 'Pilates',
  NAM_MON_POI_HOP: 'Năm môn phối hợp',
  CHEERLEADING: 'Cheerleading',
  MUA_COT: 'Múa cột',
  BONG_DA_MINI: 'Bóng đá mini',
  DUA_XE_O_TO: 'Đua xe ô tô',
  DUA_MOTOR_THE_THAO: 'Đua môtô thể thao',
  DUA_XE_DAP: 'Đua xe đạp',
  BODY_COMBAT: 'Body Combat',
  JIU_JITSU: 'Jiu-jitsu',
  CHAY_BO: 'Chạy bộ',
  TRUOT_VAN: 'Trượt ván',
  BONG_DA: 'Bóng đá',
  QUAN_VOT: 'Quần vợt',
  TRUOT_BANG: 'Trượt băng',
  HOCKEY: 'Hockey',
  BONG_RO: 'Bóng rổ',
  TAP_GYM: 'Tập gym',
  CRICKET: 'Cricket',
  NANG_TA: 'Nâng tạ',
  DAU_VAT: 'Đấu vật',
  CHAY_MARATHON: 'Chạy marathon',
  VO_THUAT: 'Võ thuật',
  BODY_JAM: 'Body Jam',
  PADEL: 'Padel',
  BODY_PUMP: 'Body Pump',
  BODY_STEP: 'Body Step',
  CUOI_NGUA: 'Cưỡi ngựa',
  BONG_CHAY: 'Bóng chày',
  TENNIS_BAI_BIEN: 'Tennis bãi biển',
  DUA_XE_MAY: 'Đua xe máy',
  THE_DUC_NGHE_THUAT: 'Thể dục nghệ thuật',
  BAN_CUNG: 'Bắn cung',
  CROSSFIT: 'CrossFit',
  LEO_NUI: 'Leo núi',
  DAP_XE: 'Đạp xe',
  BA_MON_POI_HOP: 'Ba môn phối hợp',
  MEME: 'Meme',
  METAVERSE: 'Metaverse',
  TIKTOK: 'TikTok',
  TWITCH: 'Twitch',
  NETFLIX: 'Netflix',
  SANG_TAC_NHAC: 'Sáng tác nhạc',
  FREELANCE: 'Freelance',
  NHIEP_ANH: 'Nhiếp ảnh',
  VU_DIEU_SAMBA: 'Vũ điệu Samba',
  KHOI_NGHIEP: 'Khởi nghiệp',
  HOP_XUONG: 'Hip-hop',
  COSPLAY: 'Cosplay',
  SANG_TAO_NOI_DUNG: 'Sáng tạo nội dung',
  HINH_XAM: 'Hình xăm',
  DAU_TU: 'Đầu tư',
  THOI_TRANG_VINTAGE: 'Thời trang vintage',
  VU_DIEU_VOGUE: 'Vũ điệu Vogue',
  HAT: 'Hát',
  THO: 'Thơ',
  TRIEN_LAM: 'Triển lãm',
  DAU_THO: 'Đầu thỏ',
  GIAY_SNEAKER: 'Giày sneaker',
  GIAO_LUU_NGON_NGU: 'Giao lưu ngôn ngữ',
  CHOI_GUITAR: 'Chơi guitar',
  VU_DIEU_TANGO: 'Vũ điệu Tango',
  VE: 'Vẽ',
  VIET: 'Viết',
  VAN_HOC: 'Văn học',
  SON: 'Son',
  UPCYCLING: 'Upcycling',
  CHOI_SAXOPHONE: 'Chơi saxophone',
  NHAY: 'Nhảy',
  CHUONG_TRINH_DU_HOC_TRAO_DOI: 'Chương trình du học trao đổi',
  NGHE_THUAT: 'Nghệ thuật',
  FLAMENCO: 'Flamenco',
  TO_CHUC_TU_TRI_PHI_TAP_TRUNG: 'Tổ chức tự trị phi tập trung',
  BAT_DONG_SAN: 'Bất động sản',
  CHOI_TRONG: 'Chơi trống',
  NFT: 'NFT',
  MUA_BA_LE: 'Múa ba lê',
  CHOI_DAN_BASS: 'Chơi đàn bass',
  ACAPELLA: 'Acapella',
  NHAC_CU: 'Nhạc cụ',
  VIET_NHAC: 'Viết nhạc',
  VIET_BLOG: 'Viết blog',
  THOI_TRANG: 'Thời trang',
  TU_LAM_DO_DIY: 'Tự làm đồ DIY',
  CHUNG_KHOAN: 'Chứng khoán',
  CO_PHIEU: 'Cổ phiếu',
  BOI_BAI_TAROT: 'Bói bài Tarot',
  SPA: 'Spa',
  CHAM_SOC_BAN_THAN: 'Chăm sóc bản thân',
  PHAT_TRIEN_BAN_THAN: 'Phát triển bản thân',
  HOT_YOGA: 'Hot yoga',
  THIEN: 'Thiền',
  CHAM_SOC_DA: 'Chăm sóc da',
  TRANG_DIEM: 'Trang điểm',
  VINYASA: 'Vinyasa',
  CHIEM_TINH: 'Chiêm tinh',
  DI_XONG_HOI: 'Đi xông hơi',
  CHANH_NIEM: 'Chánh niệm',
  PHONG_CACH_SONG_NANG_DONG: 'Phong cách sống năng động',
  TAP_YOGA: 'Tập yoga',
  PHIM_TRUYEN_HINH_HAN_QUOC: 'Phim truyền hình Hàn Quốc',
  RUNNING_MAN: 'Running Man',
  RAP_VIET: 'Rap Việt',
  ANIME: 'Anime',
  PHIM_HANH_DONG: 'Phim hành động',
  PHIM_HOAT_HINH: 'Phim hoạt hình',
  PHIM_TOI_PHAM: 'Phim tội phạm',
  PHIM_VIEN_TUONG: 'Phim viễn tưởng',
  PHIM_TAI_LIEU: 'Phim tài liệu',
  PHIM_CHINH_KI: 'Phim chính kịch',
  TRUYEN_HINH_THUC_TE: 'Truyền hình thực tế',
  PHIM_HAI_TINH_CAM: 'Phim hài tình cảm',
  CHUONG_TRINH_THE_THAO: 'Chương trình thể thao',
  PHIM_KINH_DI: 'Phim kinh dị',
  PHIM_INDIE: 'Phim indie',
  BOLLYWOOD: 'Bollywood',
  PHIM_ANH: 'Phim Anh',
  HAI_KI: 'Hài kịch',
  GROUP_X: 'Group X',
  FREELETICS: 'Freeletics',
  THE_DUC_NHIP_DIEU: 'Thể dục nhịp điệu',
  BAN_SUNG_THE_THAO: 'Bắn súng thể thao',
  KARATE: 'Karate',
  KHUC_CON_CAU_TREN_BANG: 'Khúc côn cầu trên băng',
  TAEKWONDO: 'Taekwondo',
};

export const DESCRIPTIONS = [
  'Tôi là người thích khám phá và học hỏi điều mới.',
  'Tôi luôn nỗ lực để hoàn thiện bản thân mỗi ngày.',
  'Tôi yêu thích sự sáng tạo và không ngại thử thách.',
  'Tôi là người hướng nội nhưng rất thân thiện.',
  'Tôi thích làm việc nhóm và chia sẻ kiến thức.',
  'Tôi luôn tìm kiếm cơ hội để phát triển bản thân.',
  'Tôi là người có trách nhiệm và đáng tin cậy.',
  'Tôi thích sự ngăn nắp và có tổ chức trong công việc.',
  'Tôi là người lạc quan và luôn nhìn về phía trước.',
  'Tôi thích giúp đỡ người khác và tạo ra giá trị.',
  'Tôi là người kiên nhẫn và bình tĩnh trong mọi tình huống.',
  'Tôi thích đọc sách và tìm hiểu về các lĩnh vực mới.',
  'Tôi là người có tư duy logic và phân tích tốt.',
  'Tôi thích tham gia các hoạt động ngoại khóa và cộng đồng.',
  'Tôi là người có khả năng thích nghi nhanh với môi trường mới.',
  'Tôi thích sự tự do và không thích bị gò bó.',
  'Tôi là người có đam mê với công nghệ và đổi mới.',
  'Tôi thích sự yên tĩnh và không gian riêng tư.',
  'Tôi là người có khả năng lãnh đạo và truyền cảm hứng.',
  'Tôi thích sự đơn giản và không phức tạp hóa vấn đề.',
  'Tôi là người có tinh thần trách nhiệm cao.',
  'Tôi thích sự chính xác và tỉ mỉ trong công việc.',
  'Tôi là người có khả năng giao tiếp tốt.',
  'Tôi thích sự thay đổi và không ngại thử điều mới.',
  'Tôi là người có tầm nhìn xa và chiến lược.',
  'Tôi thích sự hài hước và luôn tạo không khí vui vẻ.',
  'Tôi là người có khả năng làm việc độc lập.',
  'Tôi thích sự cạnh tranh và không ngại thách thức.',
  'Tôi là người có đam mê với nghệ thuật và sáng tạo.',
  'Tôi thích sự yên bình và không thích xung đột.',
  'Tôi là người có khả năng giải quyết vấn đề nhanh chóng.',
  'Tôi thích sự minh bạch và rõ ràng trong mọi việc.',
  'Tôi là người có tinh thần học hỏi không ngừng.',
  'Tôi thích sự đa dạng và không thích sự nhàm chán.',
  'Tôi là người có khả năng thuyết phục người khác.',
  'Tôi thích sự cân bằng giữa công việc và cuộc sống.',
  'Tôi là người có khả năng quản lý thời gian tốt.',
  'Tôi thích sự chân thành và thẳng thắn.',
  'Tôi là người có khả năng làm việc dưới áp lực.',
  'Tôi thích sự sôi động và không khí náo nhiệt.',
  'Tôi là người có khả năng thích nghi với mọi hoàn cảnh.',
  'Tôi thích sự tò mò và không ngừng khám phá.',
  'Tôi là người có khả năng lắng nghe và thấu hiểu.',
  'Tôi thích sự đổi mới và không ngại thay đổi.',
  'Tôi là người có khả năng làm việc nhóm hiệu quả.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng truyền đạt ý tưởng rõ ràng.',
  'Tôi thích sự cầu tiến và luôn phấn đấu vươn lên.',
  'Tôi là người có khả năng quản lý dự án tốt.',
  'Tôi thích sự hòa đồng và dễ dàng kết bạn.',
  'Tôi là người có khả năng sáng tạo và đổi mới.',
  'Tôi thích sự chính trực và không thích gian dối.',
  'Tôi là người có khả năng làm việc trong môi trường đa văn hóa.',
  'Tôi thích sự tận tâm và không ngại hy sinh.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
  'Tôi thích sự linh hoạt và không cứng nhắc.',
  'Tôi là người có khả năng làm việc với nhiều nhiệm vụ cùng lúc.',
  'Tôi thích sự chân thật và không thích giả tạo.',
  'Tôi là người có khả năng thích nghi với thay đổi.',
  'Tôi thích sự nhiệt tình và không ngại khó khăn.',
  'Tôi là người có khả năng làm việc trong môi trường áp lực cao.',
  'Tôi thích sự đam mê và không ngừng theo đuổi ước mơ.',
  'Tôi là người có khả năng thích nghi với mọi tình huống.',
  'Tôi thích sự sáng tạo và không ngừng đổi mới.',
  'Tôi là người có khả năng làm việc độc lập và nhóm.',
  'Tôi thích sự chủ động và không thích bị động.',
  'Tôi là người có khả năng thích nghi với công nghệ mới.',
  'Tôi thích sự cẩn thận và không bỏ qua chi tiết.',
  'Tôi là người có khả năng đưa ra quyết định nhanh chóng.',
];

export const INTERESTS_ARRAY = {
  NGUOI_YEU: ['NGUOI_YEU'],
  HEN_HO_NGHIEM_TUC: ['HEN_HO_LAU_DAI'],
  QUAN_HE_KHONG_RANG_BUOC: ['BAT_KI_DIEU_GI_CO_THE', 'QUAN_HE_KHONG_RANG_BUOC'],
  HOI_ME_PHIM: [
    'PHIM_TRUYEN_HINH_HAN_QUOC',
    'PHIM_HANH_DONG',
    'PHIM_HOAT_HINH',
    'PHIM_TOI_PHAM',
    'PHIM_VIEN_TUONG',
    'PHIM_TAI_LIEU',
    'PHIM_CHINH_KI',
    'PHIM_HAI_TINH_CAM',
    'PHIM_KINH_ DI',
    'PHIM_INDIE',
    'NETFLIX',
    'ANIME',
    'XEM_PHIM_NGOAI_TROI',
  ],
  THICH_DI_NHAU: [
    'DI_CHILL_TAI_BAR',
    'QUAN_BAR',
    'KHAM_PHA_QUAN_BAR',
    'TIEC_TUNG',
    'DI_CHOI_DEM',
    'SHISHA',
    'HAPPY_HOUR',
    'KARAOKE',
  ],
  CHAM_SOC_BAN_THAN: [
    'CHAM_SOC_BAN_THAN',
    'PHAT_TRIEN_BAN_THAN',
    'SPA',
    'HOT_YOGA',
    'THIEN',
    'CHAM_SOC_DA',
    'TRANG_DIEM',
    'CHANH_NIEM',
  ],
  DU_LICH: [
    'DU_LICH',
    'DU_LICH_BUI',
    'DU_LICH_COUCHSURFING',
    'PHUOT',
    'CAM_TRANG',
    'HOAT_DONG_NGOAI_TROI',
    'LEO_NUI',
    'DI_BO_DUONG_TRUONG',
    'TOUR_DI_BO',
  ],
  YEU_THE_THAO: [
    'THE_THAO',
    'BONG_DA',
    'BONG_RO',
    'TAP_GYM',
    'CHAY_BO',
    'CROSSFIT',
    'DAP_XE',
    'TRUOT_VAN',
    'DIEN_KINH',
    'VO_THUAT',
    'NBA',
    'YOGA',
  ],
  YEU_THU_CUNG: ['CHO', 'MEO', 'THO', 'HAMSTER', 'CA'],
  YEU_SACH: [
    'VAN_HOC',
    'VIET',
    'VIET_BLOG',
    'THO',
    'HARRY_POTTER',
    'POTTERHEAD',
    'MANGA',
  ],
};
